load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

rust_library(
    name = "onnx_reader",
    srcs = ["src/lib.rs"],
    edition = "2021",
    deps = [
        "@crates//:onnx-protobuf",
        "@crates//:protobuf",
    ],
    visibility = ["//visibility:public"],
)

rust_test(
    name = "onnx_reader_test",
    crate = ":onnx_reader",
)
