load("@rules_python//python:pip.bzl", "compile_pip_requirements")
load("@bazel_skylib//rules:common_settings.bzl", "string_flag")

string_flag(
    name = "gpu_backend",
    build_setting_default = "default",
    values = [
        "default",
        "rocm",
        "cuda",
        "cpu",
    ],
)

config_setting(
    name = "is_rocm_backend",
    flag_values = {":gpu_backend": "rocm"},
)

config_setting(
    name = "is_cuda_backend",
    flag_values = {":gpu_backend": "cuda"},
)

alias(
    name = "torch",
    actual = select({
        ":is_rocm_backend": "@pypi_rocm//torch",
        "//conditions:default": "@pypi//torch",
    }),
    visibility = ["//visibility:public"],
)

alias(
    name = "torchvision",
    actual = select({
        ":is_rocm_backend": "@pypi_rocm//torchvision",
        "//conditions:default": "@pypi//torchvision",
    }),
    visibility = ["//visibility:public"],
)

compile_pip_requirements(
    name = "requirements",
    src = "requirements.txt",
    requirements_txt = "requirements_lock_cuda.txt",
)

compile_pip_requirements(
    name = "requirements_rocm",
    src = "requirements.txt",
    extra_args = [
        "--extra-index-url=https://download.pytorch.org/whl/rocm6.4",
        "--find-links=https://download.pytorch.org/whl/rocm6.4",
    ],
    requirements_txt = "requirements_lock_rocm.txt",
)

compile_pip_requirements(
    name = "requirements_darwin",
    src = "requirements.txt",
    requirements_txt = "requirements_lock_darwin.txt",
)

