module(
    name = "yft_ml_sandbox",
    version = "0.1.0",
)

bazel_dep(name = "rules_python", version = "0.36.0")

PYTHON_VERSION = "3.11"

python = use_extension("@rules_python//python/extensions:python.bzl", "python")
python.toolchain(
    python_version = PYTHON_VERSION,
)
use_repo(python, "python_3_11")

pip = use_extension("@rules_python//python/extensions:pip.bzl", "pip")
pip.parse(
    requirements_lock = "//:requirements_lock.txt",
    python_version = PYTHON_VERSION,
    hub_name = "pypi",
    experimental_extra_index_urls = ["https://download.pytorch.org/whl/rocm6.2"],
)
use_repo(pip, "pypi")