load("@rules_python//python:defs.bzl", "py_binary", "py_library", "py_test")

py_library(
    name = "mario_env",
    srcs = ["mario_env.py"],
    deps = [
        "@pypi//gym",
        "@pypi//gym_super_mario_bros",
        "@pypi//gymnasium",
        "@pypi//nes_py",
        "@pypi//numpy",
    ],
    visibility = ["//visibility:public"],
)

py_library(
    name = "train_lib",
    srcs = ["train.py"],
    deps = [
        ":mario_env",
        "@pypi//numpy",
        "@pypi//torch",
    ],
    visibility = ["//visibility:public"],
)

py_binary(
    name = "main",
    srcs = ["main.py"],
    deps = [
        ":mario_env",
        "@pypi//matplotlib",
        "@pypi//numpy",
    ],
    visibility = ["//visibility:public"],
)

py_binary(
    name = "train",
    srcs = ["train.py"],
    deps = [
        ":train_lib",
    ],
    visibility = ["//visibility:public"],
)

py_test(
    name = "mario_env_test",
    srcs = ["mario_env_test.py"],
    deps = [
        ":mario_env",
        ":train_lib",
        "@pypi//numpy",
        "@pypi//torch",
    ],
)
