load("@rules_python//python:defs.bzl", "py_binary", "py_library", "py_test")

py_library(
    name = "model_lib",
    srcs = [
        "model.py",
        "__init__.py",
    ],
    deps = [
        "@pypi//onnx",
        "@pypi//onnxscript",
        "@pypi//torch",
    ],
    visibility = ["//visibility:public"],
)

py_library(
    name = "main_lib",
    srcs = ["main.py"],
    deps = [
        ":model_lib",
    ],
    visibility = ["//visibility:public"],
)

py_binary(
    name = "export",
    srcs = ["main.py"],
    main = "main.py",
    deps = [
        ":main_lib",
    ],
    visibility = ["//visibility:public"],
    env = {
        "HSA_OVERRIDE_GFX_VERSION": "11.0.0",
    }
)

py_test(
    name = "main_test",
    srcs = ["main_test.py"],
    deps = [
        ":main_lib",
        "@pypi//onnx",
        "@pypi//torch",
    ],
)
