load("@rules_python//python:defs.bzl", "py_library", "py_test")

py_library(
    name = "yft_utils",
    srcs = [
        "__init__.py",
        "device.py",
        "nes_py_patch.py",
        "timeit.py",
    ],
    deps = [
        "@pypi//nes_py",
        "@pypi//torch",
    ],
    visibility = ["//visibility:public"],
)

py_test(
    name = "device_test",
    srcs = ["device_test.py"],
    deps = [
        ":yft_utils",
        "@pypi//torch",
    ],
)

py_test(
    name = "timeit_test",
    srcs = ["timeit_test.py"],
    deps = [
        ":yft_utils",
    ],
)

py_test(
    name = "nes_py_patch_test",
    srcs = ["nes_py_patch_test.py"],
    deps = [
        ":yft_utils",
        "@pypi//numpy",
    ],
)

