load("@rules_python//python:defs.bzl", "py_binary", "py_library")

py_binary(
    name = "main",
    srcs = ["main.py"],
    deps = [
        "//alexnet_core",
        "@pypi//asciichartpy",
        "@pypi//onnx",
        "@pypi//onnxscript",
        "@pypi//torch",
        "@pypi//torchvision",
        "@pypi//scipy",
    ],
    visibility = ["//visibility:public"],
    env = {
        "HSA_OVERRIDE_GFX_VERSION": "11.0.0",
    }
)