load("@rules_python//python:defs.bzl", "py_binary")

py_binary(
    name = "main",
    srcs = ["main.py"],
    deps = [
        "//alexnet_core",
        "//yft_utils",
        "@pypi//asciichartpy",
        "@pypi//onnx",
        "@pypi//onnxscript",
        "@pypi//torch",
        "@pypi//torchvision",
        "@pypi//scipy",
    ],
    visibility = ["//visibility:public"],
    env = select({
        "@platforms//os:osx": {
            "PYTORCH_ENABLE_MPS_FALLBACK": "1",
        },
        "@platforms//os:linux": {
            "HSA_OVERRIDE_GFX_VERSION": "11.0.0",
        },
        "//conditions:default": {},
    }),
)